### ISSUE TITLE
Tests fail with missing directory

### ISSUE THREAD

**Issue by senier** [Componolit/capdpa#24]
When running the `capdpa` tests as described in the README in a clean checkout, they fail as follows:

```
======================================================================
ERROR: test_with_template (testintegration.check_integration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/capdpa/tests/testintegration.py", line 97, in test_with_template
    "test_template_user.ads"])
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/capdpa/tests/testintegration.py", line 12, in check_integration
    map(self.cache, result, specs)
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/capdpa/tests/capdpa_test.py", line 10, in <lambda>
    cache = lambda self, res, spec: open("tests/cache/" + spec, "w").write(res)
IOError: [Errno 2] No such file or directory: 'tests/cache/test_capdpa.ads'
```

When creating `tests/cache` manually, tests succeed.

**Comment by senier** [comment]
This solves the missing directory issue. However, now I get a missing file error:

```
======================================================================
ERROR: test_nested_package (testgenerator.GenerateConstant)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/capdpa/tests/testgenerator.py", line 282, in test_nested_package
    expected = self.load("test_nested_package.txt")
  File "/home/alex/Documents/Componolit_GmbH/Devel/src/capdpa/tests/capdpa_test.py", line 13, in load
    return open("tests/data/" + spec, "r").read()
IOError: [Errno 2] No such file or directory: 'tests/data/test_nested_package.txt'

```

Looks like a missing checkin/push?

**Comment by jklmnn** [comment]
Yes I added this file today and it seems as I forgot to add it. Furthermore the current state of issue_20 will fail since the inner class of nested classes is a `RECORD` and not a `CLASS_DECL` and I haven't added a handling for `RECORD` yet.

**Comment by senier** [comment]
No problem, this is acceptable for a topic branch. Could you please push your latest non-WIP state into a `staging` branch?

**Comment by jklmnn** [comment]
https://github.com/Componolit/capdpa/tree/staging is now on the latest working state including this fix.
